# Generated by Django 4.1.7 on 2023-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_sneaker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='sneakers/'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='size',
            field=models.CharField(choices=[('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13'), ('13.5', '13.5'), ('14', '14'), ('14.5', '14.5'), ('15', '15')], max_length=5),
        ),
    ]
